spring:
  datasource:
    url: jdbc:mysql://hopephm-springboot-webservice-projectrepository-db.c8viudcjzxcs.ap-northeast-2.rds.amazonaws.com:3306/hopephm_springboot_webservice_projectrepository
    username: hopephm
    password: Gmlakd96!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: hopephm0123@gmail.com
    password: Gmlakd96!#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 922833960404-m7dtjh3i48qh4c394c6r00bm139b65mc.apps.googleusercontent.com
            client-secret: CqGeGCjU9GObSmhkLOC2hklA
          facebook:
            client-id: 791959428170554
            client-secret: c68217f8a78a2968bfd33b93facbc182

app:
  verify:
    email:
      limit_time: 3
      code_length: 6
  reset:
    pw:
      limit_time: 3
      length: 20
  mail:
    sender: Project_Repository
  file:
    save_path: /home/ec2-user/app/step1/projectrepository/resources/files/

  security:
    path:
      public: /, /oauth2/**, /create_account/**, /login/**, /logout/**, /find/**, /user/**, /search/**, /project/**, /verify/**, /js/**, /css/**, /session, /auth
    oauth2:
      client:
        registration:
          naver:
            client-id: jtuU7rN_LrjD4QkfKTd1
            client-secret: z8umJJ1mN2
          kakao:
            client-id: 4fa60f00ed73c9f3bd47d02cc1762da6
            client-secret: test

server:
  port: 8080